feat(ci): Fix coverage

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -15,14 +15,20 @@ jobs:
     name: SonarQube Trigger
     runs-on: ubuntu-latest
     steps:
+
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0  
+
       - name: Cache lcov file
         uses: actions/cache@v2
         with:
           path: coverage/lcov.info        
           key: ${{ runner.os }}-${{ inputs.PROJECT_NAME }}-lcov-${{ github.run_number }}
+
+      - name: fix code coverage paths
+        run: |
+          [ -f coverage/lcov.info ] && sed -i 's/\/home\/runner\/work\/backend\/backend\//\/github\/workspace\//g' coverage/lcov.info || echo "Not found"
 
       - name: Set PROJECT_NAME_UPPERCASE env
         run: echo "PROJECT_NAME_UPPERCASE=$(echo $PROJECT_NAME | tr a-z A-Z)" >> $GITHUB_ENV
